# this code loads the png files generated by Zoltan for Stargardt OCT data from Basel/Budapest
from tensorflow.keras.utils import Sequence
import numpy as np
import os
import settings

# complete
def get_oct_filelist(data_path, seed=816, split=0.85):
    """
    Get the paths for the oct files
    currently, seed and split are not used. data are already split.
    TODO: randomize creating train/val/test sets
    """
    try:
        if os.path.isdir(os.path.join(data_path, "train")):
            trainDir = os.path.join(data_path, "train")
            trainFiles = [os.path.join(data_path, "train", f)
                    for f in os.listdir(trainDir) if os.path.isfile(os.path.join(trainDir, f))]
    except IOError as e:
        raise Exception("Folder {} doesn't exist".format(os.path.join(data_path, "train")))

    try:
        if os.path.isdir(os.path.join(data_path, "val")):
            validateDir = os.path.join(data_path, "val")
            validateFiles = [os.path.join(data_path, "val", f)
                            for f in os.listdir(validateDir) if os.path.isfile(os.path.join(validateDir, f))]
    except IOError as e:
        raise Exception("Folder {} doesn't exist".format(os.path.join(data_path, "validate")))

    try:
        if os.path.isdir(os.path.join(data_path, "test")):
            testDir = os.path.join(data_path, "test")
            testFiles = [os.path.join(data_path, "test", f)
                            for f in os.listdir(testDir) if os.path.isfile(os.path.join(testDir, f))]
    except IOError as e:
        raise Exception("Folder {} doesn't exist".format(os.path.join(data_path, "test")))

    # Print information about the Decathlon experiment data
    print("*" * 30)
    print("=" * 30)
    print("Number of training files   = {}".format(len(trainFiles)))
    print("Number of validation files = {}".format(len(validateFiles)))
    print("Number of testing files    = {}".format(len(testFiles)))
    print("=" * 30)
    print("*" * 30)

    return trainFiles, validateFiles, testFiles

# parisa note: continue work from here
# parisa note: the code assumes that data are 3d and generates batches from individual num_slices
# probably it would be better I use the 3d dataset instead
class DatasetGenerator(Sequence):
    """
    TensorFlow Dataset from Python/NumPy Iterator
    """
    
    #complete
    def __init__(self, filenames, batch_size=8, crop_dim=[240,240], augment=False, seed=816):

        from PIL import Image
        
        img = np.array(Image.open(filenames[0]).convert("RGB")) # Load the first image

        self.slice_dim = 2  # this is the RGB channel dimension
        
        # Determine the number of slices (we'll assume this is consistent for the other images)
        # not needed 2d input images
        #self.num_slices_per_scan = img.shape[self.slice_dim]

        # If crop_dim == -1, then don't crop
        if crop_dim[0] == -1:
            crop_dim[0] = img.shape[0]
        if crop_dim[1] == -1:
            crop_dim[1] = img.shape[1]
        self.crop_dim = crop_dim

        self.filenames = filenames
        self.batch_size = batch_size

        self.augment = augment
        self.seed = seed

        self.num_files = len(self.filenames)

        self.ds = self.get_dataset()

    def preprocess_img(self, img):
        """
        Preprocessing for the image
        z-score normalize
        """
        return (img - img.mean()) / img.std()

    def preprocess_label(self, label):
        """
        Predict whole tumor. If you want to predict tumor sections, then
        just comment this out.
        """
        label[label > 0] = 1.0

        return label

    def augment_data(self, img, msk):
        """
        Data augmentation
        Flip image and mask. Rotate image and mask.
        """

        if np.random.rand() > 0.5:
            ax = np.random.choice([0,1])
            img = np.flip(img, ax)
            msk = np.flip(msk, ax)

        if np.random.rand() > 0.5:
            rot = np.random.choice([1, 2, 3])  # 90, 180, or 270 degrees

            img = np.rot90(img, rot, axes=[0,1])  # Rotate axes 0 and 1
            msk = np.rot90(msk, rot, axes=[0,1])  # Rotate axes 0 and 1

        return img, msk

    def crop_input(self, img, msk):
            """
            Randomly crop the image and mask
            """

            slices = []

            # Do we randomize?
            is_random = self.augment and np.random.rand() > 0.5

            for idx, idy in enumerate(range(2)):  # Go through each dimension

                cropLen = self.crop_dim[idx]
                imgLen = img.shape[idy]

                start = (imgLen-cropLen)//2

                ratio_crop = 0.20  # Crop up this this % of pixels for offset
                # Number of pixels to offset crop in this dimension
                offset = int(np.floor(start*ratio_crop))

                if offset > 0:
                    if is_random:
                        start += np.random.choice(range(-offset, offset))
                        if ((start + cropLen) > imgLen):  # Don't fall off the image
                            start = (imgLen-cropLen)//2
                else:
                    start = 0

                slices.append(slice(start, start+cropLen))

            return img[tuple(slices)], msk[tuple(slices)]
    
    # complete
    def generate_batch_from_files(self):
        """
        Python generator which goes through a list of filenames to load.
        The files are 3D image (slice is dimension index 2 by default). However,
        we need to yield them as a batch of 2D slices. This generator
        keeps yielding a batch of 2D slices at a time until the 3D image is
        complete and then moves to the next 3D image in the filenames.
        An optional `randomize_slices` allows the user to randomize the 3D image
        slices after loading if desired.
        
        idx: to track the number of 3d images which have been read so far. idx[0,num_filenames]
        idy: number of 2d images which have been read so far. 
            If after reading one 3d image, this number is less than the batch size, 
            we continue reading the next 3 image. idy[0,]
        idz: index for adding 3d images (files) to the queue. idz[0,1+batch_size//num_slices_per_scan]
        """
        from PIL import Image

        np.random.seed(self.seed)  # Set a random seed
        
        idx = 0
        idy = 0

        while True:

            """
            Pack N_IMAGES files at a time to queue
            """
            NUM_QUEUED_IMAGES = self.batch_size 

            for idz in range(NUM_QUEUED_IMAGES): #loop to fill a batch with 2d images from png files

                filename = self.filenames[idx]
                img_and_label = np.array(Image.open(filename).convert("RGB"), dtype=np.float32)/255
                
                img = img_and_label[:,:,1]  # the green channel is the image
                img = np.expand_dims(img, axis=-1) # to be abale to concatenate later
                img = self.preprocess_img(img)
                
                label = img_and_label[:,:,0] # the red channel is the label
                label = np.expand_dims(label, axis=-1) # to be abale to concatenate later
                label = self.preprocess_label(label)

                # Crop input and label
                img, label = self.crop_input(img, label)

                if idz == 0:
                    img_stack = img
                    label_stack = label

                else:

                    img_stack = np.concatenate((img_stack,img), axis=self.slice_dim)
                    label_stack = np.concatenate((label_stack,label), axis=self.slice_dim)

                idx += 1
                if idx >= len(self.filenames):
                    idx = 0
                    np.random.shuffle(self.filenames) # Shuffle the filenames for the next iteration

            # outside for loop inside while loop
            img = img_stack
            label = label_stack

            num_slices = img.shape[self.slice_dim] #TODO this should be equal to the number of NUM_QUEUED_IMAGES

            if self.batch_size > num_slices:
                raise Exception("Batch size {} is greater than"
                                " the number of slices in the image {}."
                                " Data loader cannot be used.".format(self.batch_size, num_slices))

            """
            We can also randomize the slices so that no 2 runs will return the same slice order
            for a given file. This also helps get slices at the end that would be skipped
            if the number of slices is not the same as the batch order.
            """
            #TODO for now augmentation is disabled            
            if self.augment:
                slice_idx = np.random.choice(range(num_slices), num_slices)
                img = img[:,:,slice_idx]  # Randomize the slices
                label = label[:,:,slice_idx]

            # these are not needed for 2d input images
            #if (idy + self.batch_size) < num_slices:  # We have enough slices for batch
            #    img_batch, label_batch = img[:,:,idy:idy+self.batch_size], label[:,:,idy:idy+self.batch_size]

            #else:  # We need to pad the batch with slices
            #    img_batch, label_batch = img[:,:,-self.batch_size:], label[:,:,-self.batch_size:]  # Get remaining slices
            
            img_batch, label_batch = img, label
            #TODO for now augmentation is disabled
            if self.augment:
                img_batch, label_batch = self.augment_data(img_batch, label_batch)

            # why to expand?
            if len(np.shape(img_batch)) == 3:
                img_batch = np.expand_dims(img_batch, axis=-1)
            if len(np.shape(label_batch)) == 3:
                label_batch = np.expand_dims(label_batch, axis=-1)

            # permute the dimension, i.e. bring channel to first position
            yield np.transpose(img_batch, [2,0,1,3]).astype(np.float32), np.transpose(label_batch, [2,0,1,3]).astype(np.float32)


            # not needed for 2d input images
            idy += self.batch_size
            if idy >= num_slices: # We finished this file, move to the next
                idy = 0
                idx += 1

            if idx >= len(self.filenames):
                idx = 0
                np.random.shuffle(self.filenames) # Shuffle the filenames for the next iteration


    def get_input_shape(self):
        """
        Get image shape
        """
        return [self.crop_dim[0], self.crop_dim[1], 1]

    def get_output_shape(self):
        """
        Get label shape
        """
        return [self.crop_dim[0], self.crop_dim[1], 1]

    def get_dataset(self):
        """
        Return a dataset
        """
        ds = self.generate_batch_from_files()

        return ds

    def __len__(self):
        return self.num_files//self.batch_size

    def __getitem__(self, idx):
        return next(self.ds)

    def plot_samples(self):
        """
        Plot some random samples
        """
        import matplotlib.pyplot as plt

        img, label = next(self.ds)

        print(img.shape)

        plt.figure(figsize=(10,10))

        slice_num = 3
        plt.subplot(2,2,1)
        plt.imshow(img[slice_num,:,:,0]);
        plt.title("MRI, Slice #{}".format(slice_num));

        plt.subplot(2,2,2)
        plt.imshow(label[slice_num,:,:,0]);
        plt.title("Tumor, Slice #{}".format(slice_num));

        slice_num = self.batch_size - 1
        plt.subplot(2,2,3)
        plt.imshow(img[slice_num,:,:,0]);
        plt.title("MRI, Slice #{}".format(slice_num));

        plt.subplot(2,2,4)
        plt.imshow(label[slice_num,:,:,0]);
        plt.title("Tumor, Slice #{}".format(slice_num));
