'''
check get_label_img_from_iowa_xml_file.py in snippets
Parisa: this code loads:
    1. the png files generated by Zoltan for Stargardt OCT data from Basel/Budapest
    2. the png files for the stargardt project
'''
from tensorflow.keras.utils import Sequence
import numpy as np
import os
import json
import settings
from scipy.ndimage import zoom

def get_2d_filelist(data_path, seed=816, split=0.85):
    """
    Get the paths to the json files, containing image and label filenames
    currently, seed and split are not used. data are already split.
    """
    for d in ["train", "val", "test"]:
        dir = os.path.join(data_path, d)
        try:
            if os.path.isdir(dir):
                img_files = [os.path.join(dir, f)
                        for f in os.listdir(dir) if os.path.isfile(os.path.join(dir, f))]
        except IOError as e:
            raise Exception("Folder {} doesn't exist".format(dir))

        if d == "train":
            trainFiles = img_files
        elif d == "val":
            valFiles = img_files
        elif d == "test":
            testFiles = img_files

    # Print information about the Decathlon experiment data
    print("*" * 30)
    print("=" * 30)
    print("Number of training files   = {}".format(len(trainFiles)))
    print("Number of validation files = {}".format(len(valFiles)))
    print("Number of testing files    = {}".format(len(testFiles)))
    print("=" * 30)
    print("*" * 30)

    return trainFiles, valFiles, testFiles

def get_label_from_iowa_xml_file(xml_file, bscan_num_for_png):
    """
    - return label array from IOWA XML file, given the B-Scan number
    - the root element in the iowa xml files is <surfaces>
    - the subelements of surfaces which are important for us is <surface_size>, <surface> and its subelements: <name>, <bscan>
    - we extract ILM and Choroid surfaces for the given bscan_num, store the surfaces in two arrays.
    - we build an array for the label_img with the same size as the image, fill it with 0 outside of the ILM-Choiroid boundaies and with 1 inside the boundaies.
    """
    import xml.etree.ElementTree as ET

    tree = ET.parse(xml_file)
    surfaces = tree.getroot() # the root element in the iowa xml files is surfaces

    size_x = int(surfaces.find('scan_characteristics/size/x').text)
    size_y = int(surfaces.find('scan_characteristics/size/y').text)
    size_z = int(surfaces.find('scan_characteristics/size/z').text)
    '''
    iowa and png have different conventions for bscan numbers (n_png = n_total - n_iowa -1)
    '''
    bscan_num_for_iowa = size_z - bscan_num_for_png -1
    ilm_arr = []
    choroid_arr = []
    for surface in surfaces.findall('surface'):
        boundary_name = surface.find('name')
        if boundary_name.text == 'ILM (ILM)':
            bscan = surface.findall('bscan')[bscan_num_for_iowa]
            for y in bscan.findall('y'):
                ilm_arr.append(int(y.text))
        elif boundary_name.text == 'Outer boundary of RPE (OB_RPE)':
            choroid_arr = []
            bscan = surface.findall('bscan')[bscan_num_for_iowa]
            for y in bscan.findall('y'):
                choroid_arr.append(int(y.text))

    label_img = np.zeros((size_y,size_x))
    for i in range(size_x):
        label_img[ilm_arr[i]:choroid_arr[i], i] = 1

    return label_img

class DatasetGenerator(Sequence):
    """
    TensorFlow Dataset from Python/NumPy Iterator
    """

    def __init__(self, filenames, batch_size=8, crop_dim=[240,240], resize_dim=(-1,-1), augment=False, seed=816):

        from PIL import Image

        # Load the first image
        if filenames[0].endswith(".png"):
            img = np.array(Image.open(filenames[0]).convert("RGB"))
        elif filenames[0].endswith(".json"):
            with open(filenames[0], 'r') as jsn:
                dict = json.load(jsn)
                img_path = dict["imagePath"]
                img = np.array(Image.open(img_path).convert("RGB"))

        self.slice_dim = 2  # this is the RGB channel dimension

        # crop_dim == -1, then don't crop
        if crop_dim[0] == -1:
            crop_dim[0] = img.shape[0]
        if crop_dim[1] == -1:
            crop_dim[1] = img.shape[1]
        self.crop_dim = crop_dim

        # resize_dim = (-1,-1), then don't resize
        self.resize_dim = resize_dim

        self.filenames = filenames
        self.batch_size = batch_size

        self.augment = augment
        self.seed = seed

        self.num_files = len(self.filenames)

        self.ds = self.get_dataset()

    def preprocess_img(self, img):
        """
        Preprocessing for the image
        z-score normalize
        """
        return (img - img.mean()) / img.std()

    def preprocess_label(self, label):
        """
        Predict whole tumor. If you want to predict tumor sections, then
        just comment this out.
        """
        label[label > 0] = 1.0

        return label

    def augment_data(self, img, msk):
        """
        Data augmentation
        Flip image and mask. Rotate image and mask.
        """

        if np.random.rand() > 0.5:
            ax = np.random.choice([0,1])
            img = np.flip(img, ax)
            msk = np.flip(msk, ax)

        if np.random.rand() > 0.5:
            rot = np.random.choice([1, 2, 3])  # 90, 180, or 270 degrees

            img = np.rot90(img, rot, axes=[0,1])  # Rotate axes 0 and 1
            msk = np.rot90(msk, rot, axes=[0,1])  # Rotate axes 0 and 1

        return img, msk

    def crop_input(self, img, msk):
            """
            Randomly crop the image and mask
            """

            slices = []

            is_random = self.augment and np.random.rand() > 0.5

            for idx, idy in enumerate(range(2)):  # Go through each dimension

                cropLen = self.crop_dim[idx]
                imgLen = img.shape[idy]

                start = (imgLen-cropLen)//2

                ratio_crop = 0.20  # Crop up this this % of pixels for offset
                # Number of pixels to offset crop in this dimension
                offset = int(np.floor(start*ratio_crop))

                if offset > 0:
                    if is_random:
                        start += np.random.choice(range(-offset, offset))
                        if ((start + cropLen) > imgLen):  # Don't fall off the image
                            start = (imgLen-cropLen)//2
                else:
                    start = 0

                slices.append(slice(start, start+cropLen))

            return img[tuple(slices)], msk[tuple(slices)]

    def resize_input(self, img, label):
        """
        resize input images using bilinear interpolation
        """
        sf_width = self.resize_dim[0]/im.shape[0] # scale factor for width
        sf_height = self.resize_dim[1]/im.shape[1] # scale factor for width
        # resize with bilinear interpolation
        img_resized = zoom(img, zoom=(sf_width, sf_height), order=1, mode='nearest')
        label_resized = zoom(label, zoom=(sf_width, sf_height), order=1, mode='nearest')
        return img_resized, label_resized

    def generate_batch_from_files(self):
        """
        Python generator which goes through a list of filenames to load.
        The files are 2D image. We need to yield them as a batch of 2D slices.
        This generator keeps yielding a batch of 2D slices at a time until all 2D images are loaded.
        An optional `randomize_slices` allows the user to randomize the slices after loading if desired.

        idx: to track the number of 2d images which have been loaded so far. idx[0,num_filenames]
        idz: index for adding 2d images (files) to the batch. idz[0,batch_size]
        """
        from PIL import Image

        np.random.seed(self.seed)  # Set a random seed

        idx = 0

        while True:

            """
            Pack N_IMAGES files at a time to queue
            """
            for idz in range(self.batch_size): #loop to fill a batch with 2d images from png files

                filename = self.filenames[idx]
                if filename.endswith(".png"):
                    img_and_label = np.array(Image.open(filename).convert("RGB"), dtype=np.float32)/255

                    img = img_and_label[:,:,1]  # the green channel is the image
                    img = np.expand_dims(img, axis=-1) # to be abale to concatenate later
                    img = self.preprocess_img(img)

                    label = img_and_label[:,:,0] # the red channel is the label
                    label = np.expand_dims(label, axis=-1) # to be abale to concatenate later
                    label = self.preprocess_label(label)
                elif filename.endswith(".json"):
                    try:
                        with open(filename, 'r') as jsn:
                            dict = json.load(jsn)
                            img_path = dict["imagePath"]
                            label_path = dict["labelPath"]
                            bscan_num_for_png = int(dict["bScanNumForPNG"])
                            rgb_img = np.array(Image.open(img_path).convert("RGB"), dtype=np.float32)/255

                            img = rgb_img[:,:,1] # all channels are the same
                            img = np.expand_dims(img, axis=-1) # to be abale to concatenate later
                            img = self.preprocess_img(img)

                            label = get_label_from_iowa_xml_file(label_path, bscan_num_for_png)
                            label = np.expand_dims(label, axis=-1) # to be abale to concatenate later
                            label = self.preprocess_label(label)

                    except json.JSONDecodeError:
                        print(f"{jsn} is not a valid JSON file.")
                else:
                    os.system.exit("Error: strange input file!", filename)

                # Crop input and label
                img, label = self.crop_input(img, label)
                # resize input after crop
                if self.resize_dim != (-1,-1):
                    img, label = self.resize_input(img, label)

                if idz == 0:
                    img_stack = img
                    label_stack = label
                else:
                    img_stack = np.concatenate((img_stack,img), axis=self.slice_dim)
                    label_stack = np.concatenate((label_stack,label), axis=self.slice_dim)

                idx += 1
                if idx >= len(self.filenames):
                    idx = 0
                    np.random.shuffle(self.filenames) # Shuffle the filenames for the next iteration

            # outside "for" loop inside "while" loop
            img = img_stack
            label = label_stack

            """
            randomize the slices so that no 2 runs will return the same slice order.
            """
            if self.augment:
                slice_idx = np.random.choice(range(self.batch_size), self.batch_size)
                img = img[:,:,slice_idx]  # Randomize the slices
                label = label[:,:,slice_idx]

            img_batch, label_batch = img, label
            if self.augment:
                img_batch, label_batch = self.augment_data(img_batch, label_batch)

            if len(np.shape(img_batch)) == 3:
                img_batch = np.expand_dims(img_batch, axis=-1)
            if len(np.shape(label_batch)) == 3:
                label_batch = np.expand_dims(label_batch, axis=-1)

            # permute the dimension, i.e. bring channel to first position
            yield np.transpose(img_batch, [2,0,1,3]).astype(np.float32), np.transpose(label_batch, [2,0,1,3]).astype(np.float32)

    def get_input_shape(self):
        """
        Get image shape
        """
        return [self.crop_dim[0], self.crop_dim[1], 1]

    def get_output_shape(self):
        """
        Get label shape
        """
        return [self.crop_dim[0], self.crop_dim[1], 1]

    def get_dataset(self):
        """
        Return a dataset
        """
        ds = self.generate_batch_from_files()

        return ds

    def __len__(self):
        return self.num_files//self.batch_size

    def __getitem__(self, idx):
        return next(self.ds)

    def plot_samples(self):
        """
        Plot some random samples
        """
        import matplotlib.pyplot as plt

        img, label = next(self.ds)

        print(img.shape)

        plt.figure(figsize=(10,10))

        slice_num = 3
        plt.subplot(2,2,1)
        plt.imshow(img[slice_num,:,:,0]);
        plt.title("MRI, Slice #{}".format(slice_num));

        plt.subplot(2,2,2)
        plt.imshow(label[slice_num,:,:,0]);
        plt.title("Tumor, Slice #{}".format(slice_num));

        slice_num = self.batch_size - 1
        plt.subplot(2,2,3)
        plt.imshow(img[slice_num,:,:,0]);
        plt.title("MRI, Slice #{}".format(slice_num));

        plt.subplot(2,2,4)
        plt.imshow(label[slice_num,:,:,0]);
        plt.title("Tumor, Slice #{}".format(slice_num));
